export const IS_AUTHENTICATED = 'IS_AUTHENTICATED'
export const SET_USER = 'SET_USER'

export const SET_NOTICEBOARD = 'SET_NOTICEBOARD'
export const SET_COURSES_NOTICEBOARD = 'SET_COURSES_NOTICEBOARD'
export const SET_SELECTED_COURSE = 'SET_SELECTED_COURSE'

export const EMPTY_NOTICEBOARD_STATE = 'EMPTY_NOTICEBOARD_STATE'
export const EMPTY_COURSES_NOTICEBOARD_STATE = 'EMPTY_COURSES_NOTICEBOARD_STATE'


export const SET_SELECTED_ATTENDANCE_COURSE = 'SET_SELECTED_ATTENDANCE_COURSE'
export const SET_SELECTED_CLASS = 'SET_SELECTED_CLASS'
export const SET_SELECTED_DAY = 'SET_SELECTED_DAY'
export const SET_ATTENDANCE_TAKEN_DAYS = 'SET_ATTENDANCE_TAKEN_DAYS'
export const SET_STUDENTS_AND_ATTENDANCE = 'SET_STUDENTS_AND_ATTENDANCE'

export const SET_ASSIGNMENT_STATE = 'SET_ASSIGNMENT_STATE'
export const SET_STUDENTS_SUBMISSIONS = 'SET_STUDENTS_SUBMISSIONS'
export const SET_DUE_ASSIGNMENTS = 'SET_DUE_ASSIGNMENTS'
export const EMPTY_ASSIGNMENT_STATE = 'EMPTY_ASSIGNMENT_STATE'